# -*- coding: utf-8 -*-
"""csvtohtml.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtoEB4wdytGi97CZJF8GaAvaDZxOqfj5
"""

import csv
with open('NY_Final_Data.csv') as csv_file:
  csv_reader = csv.reader(csv_file, delimiter=',')
  line_count = 0
  for row in csv_reader:
      if line_count == 0:
          print(f'Column names are {", ".join(row)}')
          line_count += 1
      else:
          percent = int(float(row[6]) / 5 * 100)
          print(f"<tr data-description=\"{row[4]}\"\n" + 
                f"    data-url=\"{row[5]}\">\n" +
                f"    <td class=\"details-control\">+</td>\n" +
                f"    <td>{row[0]}</td>\n" + 
                f"    <td>New York</td>\n" + 
                f"    <td>{row[2]}</td>\n" + 
                f"    <td>{row[1]}</td>\n" + 
                f"    <td>{row[3]}</td>\n" + 
                f"    <th><div class=\"ratings\">\n" + 
                f"        <div class=\"empty-stars\"></div>\n" +
                f"        <div class=\"full-stars\" style=\"width:{percent}%\"></div>\n" +
                f"        </div>\n" +
                f"    </th>\n" + 
                f"</tr>")
          line_count += 1
  print(f'Processed {line_count} lines.')